print("What is your name human?")
name = input()
print("It is nice to meet you human",name,".")
print("\n")
print("How old are you?")
age = input()
print("\n")
print("How tall are you (in meters)?")
height = input()
print("\n")
print("How much do you weigh (in kilograms)?")
weigh = input()

print("\n Calculateing results...bop beep bop")
bmi = weigh/(height **2)
print(name, "you are" ,age ,"years old and your BMI is" , bmi )
